### PR TITLE
maintenance

### PR DESCRIPTION
**Pull request by HrBDev**

### CODE REVIEW

**Comment by ignoramous** [comment]
Thanks. I haven't had the chance to test this commit, can you please confirm the app builds fine? Specifically, does it build when you generate a new `tun2socks.aar` from https://github.com/celzero/outline-go-tun2socks

**Comment by HrBDev** [comment]
I just realized that I need download a LOT to build this and failed to build it on circle ci, could you provide me a build so I can test it?

**Comment by ignoramous** [comment]
Right, it does. In that case, let me test it myself and get back to you.

**Comment by ignoramous** [comment]
Thanks!

**Pull request merged**
